apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: mongo-app
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-app
          # Run this image
          image: mongo:latest
          volumeMounts:
            - name: mongo-vol
              mountPath: /data/db
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: host-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-app
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
