apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: node-app
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: node-app
    spec:
      containers:
      - name: node-app
        # Run this image
        image: suyashmishra013/emaildb:03
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_PORT


--- 


apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-app
  ports:
    - name: tcp
      port: 8080
      targetPort: 3000
  type: LoadBalancer